/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mars.glb -t 
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-9c7bbc64d8c74acfa9ec344c0fc10e1a
Title: Mars
*/
import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFAction = any; // Assuming GLTFAction is not defined in your code snippet

type GLTFResult = GLTF & {
  nodes: {
    Sphere_Material002_0: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('../../../public/mars.glb') as GLTFResult;

  // Set the desired position for the mesh
  const position = [-20, 5, 0];

  return (
    <group {...props} dispose={null}>
      {/* Add AmbientLight for general scene illumination */}
      <ambientLight intensity={0.5} />

      {/* Add DirectionalLight for directional illumination */}
      <directionalLight position={[5, 5, 5]} intensity={0.5} />

      {/* Add PointLight for point illumination */}
      <pointLight position={[10, 10, 10]} intensity={1} castShadow />

      <mesh
        geometry={nodes.Sphere_Material002_0.geometry}
        material={materials['Material.002']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1}
        position={position} // Add the position property here
      />
    </group>
  );
}

useGLTF.preload('../../../public/mars.glb')

